Cleaning the data to get the information I want to use for the project.

In [2]:
import sys
import csv
import numpy as np
import pandas as pd

#Correcting overflow error
maxInt = sys.maxsize
decrement = True

while decrement:
    decrement = False
    try:
        csv.field_size_limit(maxInt)
    except OverflowError:
        maxInt = int(maxInt/10)
        decrement = True

path = r'.\_Projects\_data\_football_data\wc14_data\wc14_data.json'
df =  pd.read_json(path)
df.head()

,algeria-vs-russia-731814,argentina-vs-belgium-731826,argentina-vs-bosnia-herz-731777,argentina-vs-iran-731793,argentina-vs-switzerland-731821,australia-vs-netherlands-731786,australia-vs-spain-731801,belgium-vs-algeria-731781,belgium-vs-russia-731797,belgium-vs-usa-731822,...,south-korea-vs-algeria-731798,south-korea-vs-belgium-731813,spain-vs-chile-731785,spain-vs-netherlands-731769,switzerland-vs-ecuador-731775,switzerland-vs-france-731791,uruguay-vs-costa-rica-731773,uruguay-vs-england-731789,usa-vs-germany-731811,usa-vs-portugal-731796
data,"{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...",...,"{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',...","{'events': [{'event_id': None, 'outcome': '1',..."
names,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...,{'twitterUrl': 'https://twitter.com/intent/twe...

It's really messy. I think it would be good to separate each row into its own dataframe to make them easier to work with.

In [4]:
df_data, df_names = df.ix[0,:], df.ix[1,:]

My first dataframe will be one of team ids.

In [202]:
teamid_info = ['team','id']
df_team_ids = pd.DataFrame(columns = teamid_info)

In [203]:
for col in df_names.columns:
    team_id = {}
    for i in range(len(df_names[col][0]['teams'])):
        team_id[teamid_info[0]] = df_names[col][0]['teams'][0]['slug']
        team_id[teamid_info[1]] = df_names[col][0]['teams'][0]['id']    
    df_team_ids = df_team_ids.append(team_id,ignore_index=True)
    
df_team_ids = df_team_ids.drop_duplicates()
df_team_ids

                      team    id
0                  algeria  1215
1                argentina   632
5                australia   575
7                  belgium   360
10  bosnia-and-herzegovina   537
11                  brazil   614
17                cameroon   494
19                   chile   831
20                colombia   832
23              costa-rica   838
25                 croatia   535
26                 ecuador   830
27                 england   114
28                  france   368
31                 germany   357
35                   ghana  1219
36                  greece   517
37                honduras   847
39                    iran  1042
40                   italy   119
42           cote-d-ivoire  1221
43                   japan  1266
45                  mexico   659
46             netherlands   366
50                 nigeria  1216
52                portugal   359
53                  russia   536
54             south-korea  1041
56                   spain   118
58             switzerland   497
60                 uruguay   837
62                     usa   596

Now I write the dataframe to a JSON file.

In [204]:
df_team_ids.to_json("team_ids.json")

On to get a dataframe of players and the info on them that I think will be relevant.

In [205]:
relevant_info = ['name','id','height','weight','club','country','team_id','real_position', 'position', 'position_wc', 'real_position_side']
df_players = pd.DataFrame(columns = relevant_info)

In [206]:
temp2 = {}

for col in df_names.columns:
    for i in range(len(df_names[col][0]['players'])):
        for dat in relevant_info:
            temp2[dat] = df_names[col][0]['players'][i][dat]
        df_players = df_players.append(temp2,ignore_index=True)

df_players = df_players.drop_duplicates()
df_players.head()

,name,id,height,weight,club,country,team_id,real_position,position,position_wc,real_position_side
0,Sergei Ignashevitch,11225,186,84,CSKA Moscow,Russia,536,Central Defender,Defender,D,Centre
1,Alexander Kerzhakov,13229,176,63,Zenit St Petersburg,Russia,536,Striker,Forward,M-R,Centre
2,Igor Akinfeev,18090,186,69,CSKA Moscow,Russia,536,Goalkeeper,Goalkeeper,G,Unknown
3,Vassili Berezoutski,18686,189,83,CSKA Moscow,Russia,536,Central Defender,Defender,D,Centre/Right
4,Yuri Zhirkov,18689,178,75,Dynamo Moscow,Russia,536,Winger,Midfielder,M-L,Left

Now I write this to JSON.

In [207]:
df_players.to_json("player_info.json")

Next up is to build a dataframe of match ids.

In [43]:
matches_raw = []
for d in df.columns:
    matches_raw.append(d)
           
matches_semiclean = []
        
for i in matches_raw:
    s = i.split('-')
    matches_semiclean.append(s)

In [44]:
onename_country_matches = []
twoname_country_matches = []
twoname_country_matches2 = []

for i in matches_semiclean:
    i = [j for j in i if j!='vs']
    if (len(i) == 3):        
        onename_country_matches.append(i)
    else:
        twoname_country_matches.append(i)
        
for i in twoname_country_matches:
    i = [j for j in i if j!='herz']
    twoname_country_matches2.append(i)
            
for i in twoname_country_matches2:
    if('bosnia' in i):
        onename_country_matches.append(i)
        twoname_country_matches2 = [j for j in twoname_country_matches2 if j != i]

twoname_country_matches2a = []
twoname_country_matches2b = []

for i in twoname_country_matches2:
    if(i[0]=='south' or i[0]== 'costa' or i[0]=='ivory'):
        twoname_country_matches2a.append(i)
    else:
        twoname_country_matches2b.append(i)

for i in twoname_country_matches2a:
    i[1] = i[0] + ' '+i[1]
    i = i[1:]
    onename_country_matches.append(i)
    
for i in twoname_country_matches2b:
    i[1] = i[1] +' '+i[2]
    i[2] = i[3]
    i = i[:3]
    onename_country_matches.append(i)

In [45]:
match_info = ['match_id','team1','team2']
df_matches = pd.DataFrame(columns = match_info)

In [48]:
df2 = df_data
match_ids0 = []
for col in df.columns:
    match_ids0.append(col[-6:]) 
df2.columns = match_ids0

In [47]:
temp3 = {}
z = 0

for i in onename_country_matches:
    temp3[match_info[0]] = i[-1]
    temp3[match_info[1]] = i[-2]
    temp3[match_info[2]] = i[-3]
    
    df_matches = df_matches.append(temp3,ignore_index=True)

df_matches.head()

  match_id        team1      team2
0   731814       russia    algeria
1   731826      belgium  argentina
2   731793         iran  argentina
3   731821  switzerland  argentina
4   731786  netherlands  australia

In [213]:
df_matches.to_json("match_ids.json")

I think that's all I want from the df_names dataframe. Now I move on to cleaning df_data.

In [5]:
df_data.head()

,algeria-vs-russia-731814,argentina-vs-belgium-731826,argentina-vs-bosnia-herz-731777,argentina-vs-iran-731793,argentina-vs-switzerland-731821,australia-vs-netherlands-731786,australia-vs-spain-731801,belgium-vs-algeria-731781,belgium-vs-russia-731797,belgium-vs-usa-731822,...,south-korea-vs-algeria-731798,south-korea-vs-belgium-731813,spain-vs-chile-731785,spain-vs-netherlands-731769,switzerland-vs-ecuador-731775,switzerland-vs-france-731791,uruguay-vs-costa-rica-731773,uruguay-vs-england-731789,usa-vs-germany-731811,usa-vs-portugal-731796
data,"{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...",...,"{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '..."

Since I have a dataframe of match ids as reference, I decided to change the columns here to only the match id. It seemed easier to work with.

In [6]:
df_data2 = df_data

match_ids = []
for col in df_data.columns:
    match_ids.append(col[-6:])    
df_data2.columns = match_ids

In [7]:
df_data2.head()

,731814,731826,731777,731793,731821,731786,731801,731781,731797,731822,...,731798,731813,731785,731769,731775,731791,731773,731789,731811,731796
data,"{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...",...,"{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '...","{'events': [{'qualifiers': {}, 'to_y': None, '..."

Now to create a dataframe of the events in Brazil v Germany.

In [222]:
df_bra_ger_events = pd.DataFrame(columns = list(df_data2[brazil_v_germany_id][0]['events'][7].keys()))

for i in df_data2[brazil_v_germany_id][0]['events']:
    df_bra_ger_events = df_bra_ger_events.append(i,ignore_index=True)

df_bra_ger_events.head()

,sec,type,team,x,event_id,period,id,side,min,to,to_y,to_x,outcome,player_id,to_z,displaymin,field_pass,y,qualifiers
0,0,102,357,0,None,1,None,A,0,41316,None,None,1,15207,None,1,f,0,{}
1,0,102,357,0,None,1,None,A,0,15208,None,None,1,41316,None,1,f,0,{}
2,0,102,357,0,None,1,None,A,0,40691,None,None,1,15208,None,1,f,0,{}
3,0,102,357,0,None,1,None,A,0,38392,None,None,1,40691,None,1,f,0,{}
4,0,102,357,0,None,1,None,A,0,39816,None,None,1,38392,None,1,f,0,{}

Here I spotted a problem, and some panick set in. The events were not as complete as I thought, and I had no code book to reference them with. I wrote the dataframe to a JSON any way, but didn't build similar dataframes for other games.

In [ ]:
df_bra_ger_events.to_json("bra_ger_events.json")

It turns out that the dataframe that I created before weren't as immediately useful as I thought they would have been. I was stuck in No man's land between being overly general, and overly specific, with the latter being my goal to analyze Brazil versus Germany. Luckily, someone suggested that I create a dataframe that would be conducive to building a model to try to predict the score of Brazil v Germany based on stats only. 

The dataframe is composed of all 64 games from the World Cup, and the difference in frequency for each statistics between the two competitors. 

Here's how it was constructed. (Brazil v Germany was added first.)

In [10]:
brazil_v_germany_id = '731827'

df_data2[brazil_v_germany_id][0]['team_stats'].keys()

dict_keys(['614', '357'])

In [40]:
bra_ger_tstats = pd.DataFrame.from_dict(df_data2[brazil_v_germany_id][0]['team_stats'], orient='index')
bra_ger_tstats = bra_ger_tstats.fillna(0)

diff = bra_ger_tstats.ix[0]-bra_ger_tstats.ix[1]
diff['team1']=bra_ger_tstats.index[0]
diff['team2']=bra_ger_tstats.index[1]

temp = pd.DataFrame(diff)

if temp.ix['goals'][0]==0.0:
    temp['result']=0 #draw
    
elif temp.ix['goals'][0]>0:
    temp['result']=1 #win
    
elif temp.ix['goals'][0]<0.0:
    temp['result']=-1 #loss

In [41]:
diff

dispossessed                1
gk_smother                 -1
challenge_lost              2
pen_area_entries           -6
total_fwd_zone_pass        -3
att_miss_left              -1
accurate_layoffs           -1
accurate_through_ball      -1
poss_lost_ctrl             -6
rightside_pass             21
poss_won_att_3rd           -1
accurate_throws             0
accurate_flick_on          -1
accurate_keeper_sweeper     1
successful_put_through     -3
...
att_one_on_one                1
offside_provoked              3
accurate_corners_intobox      1
dive_save                     1
accurate_cross                2
good_high_claim               2
total_fastbreak               3
att_goal_high_left            1
stand_save                    1
att_goal_low_right            2
att_goal_low_centre           1
att_lf_goal                   2
att_freekick_total            1
team1                       357
team2                       614
Length: 175, dtype: object

In [50]:
print(len(diff))

175

Now I add the stats from the other 63 games.

In [148]:
#loop through df_matches match ids

count = 0
for match in df_matches.match_id:
#for each one create a series

    df_temp = pd.DataFrame.from_dict(df_data2[match][0]['team_stats'], orient='index')
    df_temp = df_temp.fillna(0)
    diff = df_temp.ix[0]-df_temp.ix[1]
    diff['team1']=df_temp.index[0]
    diff['team2']=df_temp.index[1]
    temp = pd.DataFrame(diff).transpose()
    
    try:
        if temp['goals'][0]==0.0:
            temp['result']=0
        elif temp['goals'][0]>0:
            temp['result']=1
        elif temp['goals'][0]<0.0:
            temp['result']=-1
    except:
        temp['result']=0
    
    #concat to the diff dataframe and repeat
    if count==0:
        df_all = temp
    else:
        df_all = pd.concat([df_all,temp])
    count+=1
    
print(df_all.head())

  accurate_back_zone_pass accurate_chipped_pass accurate_corners_intobox  \
0                     -43                     0                        1
0                      -8                     7                        2
0                     -94                   -17                       -3
0                     -91                    -8                       -1
0                       6                     3                        1

  accurate_cross accurate_cross_nocorner accurate_flick_on  \
0             -1                      -2                 1
0              4                       2                 4
0             -4                      -1                 3
0             -6                      -5                 4
0              1                       0                 1

  accurate_freekick_cross accurate_fwd_zone_pass accurate_goal_kicks  \
0                       2                    -43                  -2
0                     NaN                     43                   0
0                       0                   -283                   4
0                      -1                   -162                  -5
0                       1                     -5                  -6

  accurate_keeper_sweeper           ...           total_through_ball  \
0                       3           ...                          NaN
0                       1           ...                            1
0                     NaN           ...                            0
0                       1           ...                           -1
0                      -1           ...                            1

  total_throws touches turnover unsuccessful_touch was_fouled won_contest  \
0          -16    -117        3                  3         -1          -5
0            5      42        4                  4         -3          -2
0           -9    -395        1                  1         -8         -11
0          -15    -280        5                  5         -9          -1
0            0     -14       -6                 -6         -4          -6

  won_corners won_tackle yellow_card
0          -1          0           1
0           1          8           1
0          -4          1           2
0          -8          0          -1
0          -1          7           0

[5 rows x 242 columns]

Here are all the stats plus some others columns.

In [149]:
for c in df_all.columns:
    print(c)

accurate_back_zone_pass
accurate_chipped_pass
accurate_corners_intobox
accurate_cross
accurate_cross_nocorner
accurate_flick_on
accurate_freekick_cross
accurate_fwd_zone_pass
accurate_goal_kicks
accurate_keeper_sweeper
accurate_keeper_throws
accurate_launches
accurate_layoffs
accurate_long_balls
accurate_pass
accurate_pull_back
accurate_through_ball
accurate_throws
aerial_lost
aerial_won
assist_attempt_saved
assist_blocked_shot
assist_free_kick_won
assist_own_goal
assist_pass_lost
assist_penalty_won
att_assist_openplay
att_assist_setplay
att_bx_centre
att_bx_left
att_bx_right
att_cmiss_high
att_cmiss_high_left
att_cmiss_high_right
att_cmiss_left
att_cmiss_right
att_fastbreak
att_freekick_goal
att_freekick_miss
att_freekick_post
att_freekick_target
att_freekick_total
att_goal_high_centre
att_goal_high_left
att_goal_high_right
att_goal_low_centre
att_goal_low_left
att_goal_low_right
att_hd_goal
att_hd_miss
att_hd_post
att_hd_target
att_hd_total
att_ibox_blocked
att_ibox_goal
att_ibox_miss
att_ibox_post
att_ibox_target
att_lf_goal
att_lf_target
att_lf_total
att_lg_centre
att_lg_left
att_lg_right
att_miss_high
att_miss_high_left
att_miss_high_right
att_miss_left
att_miss_right
att_obox_blocked
att_obox_goal
att_obox_miss
att_obox_post
att_obox_target
att_obp_goal
att_obx_centre
att_obx_left
att_obx_right
att_obxd_left
att_obxd_right
att_one_on_one
att_openplay
att_pen_goal
att_pen_target
att_post_high
att_post_left
att_post_right
att_rf_goal
att_rf_target
att_rf_total
att_setpiece
att_sv_high_centre
att_sv_high_left
att_sv_high_right
att_sv_low_centre
att_sv_low_left
att_sv_low_right
attempted_tackle_foul
attempts_conceded_ibox
attempts_conceded_obox
backward_pass
ball_recovery
big_chance_created
big_chance_missed
big_chance_scored
blocked_cross
blocked_pass
blocked_scoring_att
challenge_lost
clean_sheet
clearance_off_line
corner_taken
cross_not_claimed
crosses_18yard
crosses_18yardplus
dangerous_play
dispossessed
dive_catch
dive_save
diving_save
duel_lost
duel_won
effective_blocked_cross
effective_clearance
effective_head_clearance
error_lead_to_goal
error_lead_to_shot
final_third_entries
formation_place
foul_throw_in
fouled_final_third
fouls
freekick_cross
fwd_pass
game_started
gk_smother
goal_assist
goal_assist_deadball
goal_assist_intentional
goal_assist_openplay
goal_assist_setplay
goal_fastbreak
goal_kicks
goals
goals_conceded
goals_conceded_ibox
goals_conceded_obox
goals_openplay
good_high_claim
hand_ball
head_clearance
head_pass
hit_woodwork
interception
interception_won
interceptions_in_box
keeper_pick_up
keeper_throws
last_man_tackle
leftside_pass
long_pass_own_to_opp
long_pass_own_to_opp_success
lost_corners
mins_played
offside_provoked
offtarget_att_assist
ontarget_att_assist
ontarget_scoring_att
open_play_pass
outfielder_block
overrun
own_goals
passes_left
passes_right
pen_area_entries
pen_goals_conceded
penalty_conceded
penalty_faced
penalty_save
penalty_won
poss_lost_all
poss_lost_ctrl
poss_won_att_3rd
poss_won_def_3rd
poss_won_mid_3rd
possession_pct
post_scoring_att
punches
put_through
red_card
result
rightside_pass
saved_ibox
saved_obox
saves
second_goal_assist
second_yellow
shield_ball_oop
shot_fastbreak
shot_off_target
six_yard_block
stand_catch
stand_save
successful_final_third_passes
successful_open_play_pass
successful_put_through
team1
team2
total_att_assist
total_back_zone_pass
total_chipped_pass
total_clearance
total_contest
total_corners_intobox
total_cross
total_cross_nocorner
total_fastbreak
total_final_third_passes
total_flick_on
total_fwd_zone_pass
total_high_claim
total_keeper_sweeper
total_launches
total_layoffs
total_long_balls
total_offside
total_pass
total_pull_back
total_scoring_att
total_sub_off
total_sub_on
total_tackle
total_through_ball
total_throws
touches
turnover
unsuccessful_touch
was_fouled
won_contest
won_corners
won_tackle
yellow_card

In [152]:
df_all.columns

Index(['index', 'accurate_back_zone_pass', 'accurate_chipped_pass', 'accurate_corners_intobox', 'accurate_cross', 'accurate_cross_nocorner', 'accurate_flick_on', 'accurate_freekick_cross', 'accurate_fwd_zone_pass', 'accurate_goal_kicks', 'accurate_keeper_sweeper', 'accurate_keeper_throws', 'accurate_launches', 'accurate_layoffs', 'accurate_long_balls', 'accurate_pass', 'accurate_pull_back', 'accurate_through_ball', 'accurate_throws', 'aerial_lost', 'aerial_won', 'assist_attempt_saved', 'assist_blocked_shot', 'assist_free_kick_won', 'assist_own_goal', 'assist_pass_lost', 'assist_penalty_won', 'att_assist_openplay', 'att_assist_setplay', 'att_bx_centre', 'att_bx_left', 'att_bx_right', 'att_cmiss_high', 'att_cmiss_high_left', 'att_cmiss_high_right', 'att_cmiss_left', 'att_cmiss_right', 'att_fastbreak', 'att_freekick_goal', 'att_freekick_miss', 'att_freekick_post', 'att_freekick_target', 'att_freekick_total', 'att_goal_high_centre', 'att_goal_high_left', 'att_goal_high_right', 'att_goal_low_centre', 'att_goal_low_left', 'att_goal_low_right', 'att_hd_goal', 'att_hd_miss', 'att_hd_post', 'att_hd_target', 'att_hd_total', 'att_ibox_blocked', 'att_ibox_goal', 'att_ibox_miss', 'att_ibox_post', 'att_ibox_target', 'att_lf_goal', 'att_lf_target', 'att_lf_total', 'att_lg_centre', 'att_lg_left', 'att_lg_right', 'att_miss_high', 'att_miss_high_left', 'att_miss_high_right', 'att_miss_left', 'att_miss_right', 'att_obox_blocked', 'att_obox_goal', 'att_obox_miss', 'att_obox_post', 'att_obox_target', 'att_obp_goal', 'att_obx_centre', 'att_obx_left', 'att_obx_right', 'att_obxd_left', 'att_obxd_right', 'att_one_on_one', 'att_openplay', 'att_pen_goal', 'att_pen_target', 'att_post_high', 'att_post_left', 'att_post_right', 'att_rf_goal', 'att_rf_target', 'att_rf_total', 'att_setpiece', 'att_sv_high_centre', 'att_sv_high_left', 'att_sv_high_right', 'att_sv_low_centre', 'att_sv_low_left', 'att_sv_low_right', 'attempted_tackle_foul', 'attempts_conceded_ibox', ...], dtype='object')

Finally, I wrote the dataframe to both JSON and CSV.

In [156]:
df_all.to_json("wc_data.json")
df_all.to_csv('wc_data.csv', index=False)